project                  = "three-tier"
environment              = "prod"
region                   = "ap-south-1"
vpc_cidr                 = "10.1.0.0/16"
public_subnet_cidrs      = ["10.1.1.0/24", "10.1.2.0/24"]
private_app_subnet_cidrs = ["10.1.11.0/24", "10.1.12.0/24"]
private_db_subnet_cidrs  = ["10.1.21.0/24", "10.1.22.0/24"]
single_nat_gateway       = false
instance_type            = "t3.micro"
asg_min_size             = 2
asg_max_size             = 4
asg_desired_capacity     = 2
db_instance_class        = "db.t3.small"
db_multi_az              = true
db_backup_retention_days = 7
db_deletion_protection   = true
db_skip_final_snapshot   = false
